
name: RANC Hardware Unit Tests

on:
  push:
    branches: [ master ]
    paths: [ 'hardware/*', '.github/workflows/hardware_unit_tests.yml' ]
  pull_request:
    branches: [ master ]
    paths: [ 'hardware/*', '.github/workflows/hardware_unit_tests.yml' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6 ]
    defaults:
      run:
        shell: bash
        working-directory: hardware

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y iverilog git
        python -m pip install --upgrade pip
        pip install myhdl pytest pytest-xdist
    - name: Build iverilog object files
      run: |
        cd src/simulations/iverilog
        make
    - name: Lint with flake8
      run: |
        cd src/simulations
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Unit Tests with pytest
      run: |
        pytest -n auto --dist=loadfile src/simulations/tests
